# Generated by Django 4.1.5 on 2024-03-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainshares',
            options={'verbose_name': 'Main Shares', 'verbose_name_plural': 'Main Shares'},
        ),
        migrations.AddField(
            model_name='mainshares',
            name='name',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
