# Generated by Django 5.0.3 on 2024-05-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_alter_shareids_isin_alter_shareids_wkn'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareids',
            name='alterName',
            field=models.CharField(default='', max_length=64, verbose_name='Alternative Name'),
        ),
    ]
