# Generated by Django 5.0.3 on 2024-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_category_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('sell', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('buy', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search History Entries',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Link Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='mainshares',
            name='name',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
