# Generated by Django 4.1.5 on 2024-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_shareids_altername'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareids',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='shareids',
            name='isEtf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shareids',
            name='alterName',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Alternative Name'),
        ),
    ]
