# Generated by Django 4.1.5 on 2024-04-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_searchhistory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshares',
            name='isin',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AddField(
            model_name='mainshares',
            name='wkn',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
