# Generated by Django 4.1.5 on 2024-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_shareids_currency_shareids_isetf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attrNames',
            fields=[
                ('source', models.CharField(choices=[('comdirect', 'Comdirect'), ('es', 'Effektenspiegel'), ('scalable', 'Scalable')], max_length=32, primary_key=True, serialize=False)),
                ('attrName', models.CharField(max_length=32)),
                ('attrIsin', models.CharField(max_length=32)),
                ('attrWkn', models.CharField(max_length=32)),
                ('attrCurrency', models.CharField(max_length=32)),
                ('attrEtf', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Attribut Names for Stock Infos',
                'verbose_name_plural': 'Attribut Names for Stock Infos',
            },
        ),
    ]
