# Generated by Django 4.1.5 on 2024-04-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_mainshares_isin_mainshares_wkn'),
    ]

    operations = [
        migrations.CreateModel(
            name='shareIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=32)),
                ('symbol', models.CharField(max_length=12)),
                ('wkn', models.CharField(default='None', max_length=6)),
                ('isin', models.CharField(default='None', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainshares',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='mainshares',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mainshares',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='mainshares',
            name='wkn',
        ),
        migrations.AddField(
            model_name='mainshares',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='blogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headLine', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('summary', models.TextField()),
                ('plannedAction', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shareInfos', models.ManyToManyField(to='myportfolio.shareids')),
            ],
            options={
                'verbose_name': 'Blog Entry',
                'verbose_name_plural': 'Blog Entries',
            },
        ),
        migrations.AddField(
            model_name='mainshares',
            name='shareInfos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.shareids'),
            preserve_default=False,
        ),
    ]
