# Generated by Django 4.1.5 on 2024-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_shareids_remove_mainshares_isin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareids',
            name='isMainShare',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MainShares',
        ),
    ]
