# Generated by Django 4.1.5 on 2024-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_attrnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='strategyShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('month', 'Month'), ('onetime', 'Onetime'), ('planned', 'Planned')], max_length=8)),
                ('invest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attrnames',
            options={'verbose_name': 'Config: Attribut Names for Stock Infos', 'verbose_name_plural': 'Config: Attribut Names for Stock Infos'},
        ),
    ]
