# Generated by Django 4.1.5 on 2024-04-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_shareids_ismainshare_delete_mainshares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='shareInfos',
            field=models.ManyToManyField(to='myportfolio.shareids', verbose_name='Referenced Stocks'),
        ),
    ]
