# Generated by Django 4.1.5 on 2024-04-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_alter_blogentry_shareinfos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='shareInfos',
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='headLine',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='plannedAction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='source',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='blog_shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.blogentry')),
                ('shares_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.shareids')),
            ],
        ),
    ]
