# Generated by Django 4.1.5 on 2024-05-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_alter_strategy_options_alter_strategyshares_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategyshares',
            unique_together={('strategy_name', 'shares_name')},
        ),
    ]
