# Generated by Django 4.1.5 on 2024-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_remove_blogentry_shareinfos_alter_blogentry_headline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_shares',
            options={'verbose_name': 'In Blog referenced Stocks', 'verbose_name_plural': 'In Blog referenced Stocks'},
        ),
        migrations.AlterField(
            model_name='shareids',
            name='isin',
            field=models.CharField(blank=True, default='None', max_length=12),
        ),
        migrations.AlterField(
            model_name='shareids',
            name='symbol',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='shareids',
            name='wkn',
            field=models.CharField(blank=True, default='None', max_length=6),
        ),
    ]
