# Generated by Django 4.1.5 on 2024-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_alter_blog_shares_options_alter_shareids_isin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='picture_url',
            field=models.URLField(blank=True),
        ),
    ]
