# Generated by Django 4.1.5 on 2024-05-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_alter_strategyshares_strategy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyshares',
            name='shares_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.shareids'),
        ),
    ]
