# Generated by Django 4.1.5 on 2024-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0011_blogentry_picture_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareids',
            options={'verbose_name': 'Share/Stock IDs', 'verbose_name_plural': 'Share/Stock IDs'},
        ),
    ]
