# Generated by Django 4.1.5 on 2024-05-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0011_alter_strategyshares_shares_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyshares',
            name='numberShares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
