# Generated by Django 4.1.5 on 2024-05-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0012_strategyshares_numbershares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyshares',
            name='status',
            field=models.CharField(choices=[('month', 'Month'), ('month m.', 'Month manually'), ('onetime', 'Onetime'), ('planned', 'Planned')], max_length=8),
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numberShares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('info', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shares_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.shareids')),
            ],
        ),
    ]
