# Generated by Django 4.1.5 on 2024-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0012_alter_shareids_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='referencedStocks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='blog_shares',
            unique_together={('blog_id', 'shares_id')},
        ),
    ]
