# Generated by Django 4.1.5 on 2024-05-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0013_alter_strategyshares_status_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactions',
            new_name='transaction',
        ),
    ]
