# Generated by Django 4.1.5 on 2024-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0013_blogentry_referencedstocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='stocksProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
