# Generated by Django 4.1.5 on 2024-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0014_blogentry_stocksprocessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='referencedStocks',
            field=models.TextField(blank=True, help_text='Use this Colab https://colab.research.google.com/drive/1yhgrlksevpURUSeDHN9RnU-lqWELjeCi?usp=sharing'),
        ),
    ]
