# Generated by Django 4.1.5 on 2024-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0015_upload_alter_attrnames_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrnames',
            name='attrNumber',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='attrnames',
            name='attrValue',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='attrnames',
            name='source',
            field=models.CharField(choices=[('comdirect', 'Extract Comdirect Share Names, WKN and ISIN'), ('comdirect portfolio', 'Extract Comdirect Portfolio'), ('es', 'Effektenspiegel'), ('scalable', 'Scalable')], max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploadData',
            field=models.CharField(choices=[('comdirect', 'Extract Comdirect Share Names, WKN and ISIN'), ('comdirect portfolio', 'Extract Comdirect Portfolio'), ('es', 'Effektenspiegel'), ('scalable', 'Scalable')], max_length=32, primary_key=True, serialize=False),
        ),
    ]
